keys:
  - &armeen 098A271A852C8A79A0DAEFB34C66EC973CCB0599
  - &lithium age1w284qj7mvpgu433yervradrkt6fg9spfkklx97547tlld0qeev3qxtc2c7
creation_rules:
  - path_regex: hosts/lithium/secrets/[^/]+\..*$
    key_groups:
    - pgp:
      - *armeen
      age:
      - *lithium
