#!/usr/bin/env bash

if hash nom 2>/dev/null; then
  cmd=nom
else
  cmd=nix
fi

if [[ -n "$1" && "$1" != -* ]]; then
  hostname=$1
elif [[ "$OSTYPE" == "darwin"* ]]; then
  hostname=$(hostname -s)
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  hostname=$(hostname)
else
  echo "Unknown OS type: $OSTYPE"
  exit 1
fi

$cmd build ".#configurations.$hostname.config.system.build.toplevel" --keep-going "$@"
