#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  cmd=("sudo" "darwin-rebuild" "--flake" "." "switch")
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  if hash nh 2>/dev/null; then
    cmd=("nh" "os" "switch")
  else
    cmd=("nixos-rebuild" "--sudo" "--flake" "." "switch")
  fi
else
  echo "Unknown OS type: $OSTYPE"
  exit 1
fi

"${cmd[@]}" "$@"
